
// user
export const SET_USER_NAME = 'SET_USER_NAME'

// contributor 
export const SHOW_ALL_CONTRIBUTORS = 'SHOW_ALL_CONTRIBUTORS'
export const SHOW_TOP_CONTRIBUTORS = 'SHOW_TOP_CONTRIBUTORS'
export const FETCH_REACT_CONTRI = 'FETCH_REACT_CONTRI'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
